# This is a basic workflow to help you get started with Actions

name: CI
permissions:
  contents: read

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: n80fr1n60/secure-checkout@c64cb640a80cda75c4172528782e3c79e05a58fd # v1.0.0      
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Try to fetch with no credentials
        run: |
          echo "---- secure checkout 1----"
          set -x
          git config --get credential.helper || echo "none"
          cat .git/config
          echo "---- secure checkout 2----"
          cat .git/config | grep AUTHORIZATION || echo "none"      
          
      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: false

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
