name: Issues

on:
  issues:
    types:
      - opened

jobs:
  print_issue_title:
    runs-on: ubuntu-latest
    steps:
      - name: Print Issue Title
        run: echo "${{ github.event.issue.title }}"

